@Server_HostAddress = https://localhost:7230

// Query Controller

### Get Concept
GET {{Server_HostAddress}}/api/query?topic=cpu scheduler

### Get Concept (streamed)
GET {{Server_HostAddress}}/api/query/stream?topic=cpu scheduler
